version: "3.7"

services:

  sakiladb:
    image: frantiseks/postgres-sakila
    restart: always
    environment:
      POSTGRES_PASSWORD: sakila
    expose:
      - 5432
    networks:
      - spring-cloud-network

  spring-boot-jdbc:
    container_name: spring-boot-jdbc
    build:
      context: spring-boot-jdbc
      dockerfile: Dockerfile
    image: spring-boot-jdbc:latest
    ports:
      - 8081:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker_compose
    networks:
      - spring-cloud-network

  spring-boot-jooq:
    container_name: spring-boot-jooq
    build:
      context: spring-boot-jooq
      dockerfile: Dockerfile
    image: spring-boot-jooq:latest
    ports:
      - 8082:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker_compose
    networks:
      - spring-cloud-network

  spring-data-jdbc:
    container_name: spring-data-jdbc
    build:
      context: spring-data-jdbc
      dockerfile: Dockerfile
    image: spring-data-jdbc:latest
    ports:
      - 8083:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker_compose
    networks:
      - spring-cloud-network

networks:
    spring-cloud-network:
        driver: bridge
