openapi: 3.0.1
info:
  title: Film API
  version: v1
servers:
  - url: http://localhost:8080
    description: Generated server url
tags:
  - name: film
    description: REST endpoints over the Actor Entity/AggregateRoot  in Sakila DB
paths:
  /api/v1/films:
    get:
      tags:
        - films
      operationId: get_films
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Films'
components:
  schemas:
    Films:
      type: array
      items:
        $ref: '#/components/schemas/Film'
    Film:
      type: object
      properties:
        film_id:
          type: integer
          format: int64
          description: unique identifier for any film
        title:
          type: string
          format: int64
          description: Film movie
