name: CI Builds

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '21'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Maven Verify
        run: |
          ./mvnw --batch-mode --no-transfer-progress verify

      - name: Docker compose verification
        run: |
          cd docs/schema-spy/
          docker build . -f Dockerfile -t schema-spy-local
          cd ../../
          docker-compose -f docker-compose.yml up -d
          sleep 50
          curl http://localhost:8081/api/v1/films
          curl http://localhost:8082/api/v1/films
          curl http://localhost:8083/api/v1/films
          curl http://localhost:8086/api/v1/films
          curl http://localhost:8085/api/v1/films
          docker logs schemaspy
          docker-compose -f docker-compose.yml stop
